#//////////////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////////////
# ------------------ Fastfusion Parameters ----------------------------
#//////////////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////////////


# Desired Threading
threadFusion : true
threadMeshing : true

# Scales
imageScale : 5000.0
scale : 0.01
distanceThreshold : 0.01

# Depth Consistency Checks
depthConsistencyChecks : 10

# Mesh Saving (location + desired Name without ending)
saveMesh : true
fileLocation : /home/karrer/Poster
# TF Id's
world_id : /vicon
cam_id : /depth

# Define if using Time of flight sensor or not
use_pmd : true
