#//////////////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////////////
# ------------------ Fastfusion Parameters ----------------------------
#//////////////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////////////


# Desired Threading
threadFusion : true
threadMeshing : true

# Scales
imageScale : 1000.0
scale : 0.009
distanceThreshold : 0.03

# Depth Consistency Checks
depthConsistencyChecks : 0

# Mesh Saving (location + desired Name without ending)
saveMesh : true
fileLocation : /home/karrer/forPaper
# TF Id's
world_id : /world
cam_id : /realsense_frame
use_slam : false


# Define if using Time of flight sensor or not
use_pmd : false
depth_noise: true
