#//////////////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////////////
# ------------------ Fastfusion Parameters ----------------------------
#//////////////////////////////////////////////////////////////////////
#//////////////////////////////////////////////////////////////////////


# Desired Threading
threadFusion : true
threadMeshing : true

# Scales
imageScale : 1000.0
scale : 0.005
threshold : 0.005

# Depth Consistency Checks
depthConsistencyChecks : 10

# Mesh Saving (location + desired Name without ending)
saveMesh : true
fileLocation : /home/karrer/Poster
# TF Id's
world_id : /vicon
cam_id : /camera_imu

# Define if using Time of flight sensor or not
use_pmd : false
